services:
  telegram-api-proxy:
    image: telegram-api-proxy:latest
    container_name: telegram-api-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
